project_id = "seqqfrtnrjngvqidtrcp"

[functions.get-public-holidays]
verify_jwt = false

[functions.assign-telegram-bot]
verify_jwt = false

[functions.update-telegram-bot]
verify_jwt = false

[functions.ai-daily-summary]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-join-request]
verify_jwt = false

[functions.attendance-reminders]
verify_jwt = false

[functions.notify-employee]
verify_jwt = false
